// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ESA.Core.Entities
{
    public partial class AccountSurvey
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public string MediaInfo { get; set; }
        public string RecommendedBy { get; set; }
        public DateTime LastUpdate { get; set; }

        public virtual Account Account { get; set; }
    }
}