// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ESA.Core
{
    public partial class AccountProfile
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public DateOnly? DateOfBirth { get; set; }
        public string NationalityCode { get; set; }
        public string CityName { get; set; }
        public string PhoneNumber { get; set; }
        public string AboutMe { get; set; }
        public DateTime LastUpdate { get; set; }
        public string ZoomLink { get; set; }

        public virtual Account Account { get; set; }
    }
}