// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ESA.Core
{
    public partial class Account
    {
        public Account()
        {
            CourseCalendar = new HashSet<CourseCalendar>();
            CourseStudent = new HashSet<CourseStudent>();
            CourseStudentGroup = new HashSet<CourseStudentGroup>();
            Refund = new HashSet<Refund>();
            StudentPacks = new HashSet<StudentPacks>();
        }

        public int Id { get; set; }
        public short RoleId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public byte[] ProfilePicture { get; set; }
        public bool IsActive { get; set; }
        public DateTime LastUpdate { get; set; }
        /// <summary>
        /// URL from Auth0
        /// </summary>
        public string ProfilePicturePath { get; set; }

        public virtual Role Role { get; set; }
        public virtual AccountProfile AccountProfile { get; set; }
        public virtual AccountSurvey AccountSurvey { get; set; }
        public virtual ICollection<CourseCalendar> CourseCalendar { get; set; }
        public virtual ICollection<CourseStudent> CourseStudent { get; set; }
        public virtual ICollection<CourseStudentGroup> CourseStudentGroup { get; set; }
        public virtual ICollection<Refund> Refund { get; set; }
        public virtual ICollection<StudentPacks> StudentPacks { get; set; }
    }
}