// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ESA.Core
{
    public partial class Coupons
    {
        public int Id { get; set; }
        public string Coupon { get; set; }
        public int Discount { get; set; }
        public bool IsActive { get; set; }
    }
}