// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ESA.Core.Entities
{
    public partial class CourseStudentGroup
    {
        public int Id { get; set; }
        public int CourseCalendarId { get; set; }
        public int StudentId { get; set; }
        public decimal Progress { get; set; }
        public bool? IsActive { get; set; }
        public bool IsCancelled { get; set; }
        public bool? PaymentConfirmed { get; set; }
        public bool InvoiceConfirmed { get; set; }
        public DateTime EnrolledDate { get; set; }
        public DateTime LastUpdate { get; set; }

        public virtual CourseCalendar CourseCalendar { get; set; }
        public virtual Account Student { get; set; }
    }
}