// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ESA.Core
{
    public partial class CourseReview
    {
        public int Id { get; set; }
        public int CourseCalendarId { get; set; }
        public int CourseStudentId { get; set; }
        public string Comment { get; set; }
        public float Rating { get; set; }
        public DateTime LastUpdate { get; set; }

        public virtual CourseCalendar CourseCalendar { get; set; }
        public virtual CourseStudent CourseStudent { get; set; }
    }
}