// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ESA.Core
{
    public partial class CourseCalendar
    {
        public CourseCalendar()
        {
            CourseReview = new HashSet<CourseReview>();
            CourseSchedule = new HashSet<CourseSchedule>();
            CourseStudentGroup = new HashSet<CourseStudentGroup>();
        }

        public int Id { get; set; }
        public int CourseId { get; set; }
        /// <summary>
        /// Assigned teacher
        /// </summary>
        public int TeacherId { get; set; }
        public DateOnly StartDate { get; set; }
        public DateOnly FinishDate { get; set; }
        public bool IsActive { get; set; }
        public DateTime LastUpdate { get; set; }

        public virtual Course Course { get; set; }
        public virtual Account Teacher { get; set; }
        public virtual ICollection<CourseReview> CourseReview { get; set; }
        public virtual ICollection<CourseSchedule> CourseSchedule { get; set; }
        public virtual ICollection<CourseStudentGroup> CourseStudentGroup { get; set; }
    }
}