// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ESA.Core.Entities
{
    public partial class CourseStudent
    {
        public CourseStudent()
        {
            CourseReview = new HashSet<CourseReview>();
            CourseStudentFriend = new HashSet<CourseStudentFriend>();
            InvoiceDetail = new HashSet<InvoiceDetail>();
        }

        public int Id { get; set; }
        public int CourseScheduleId { get; set; }
        public int StudentId { get; set; }
        public decimal Progress { get; set; }
        public bool IsActive { get; set; }
        public bool IsCancelled { get; set; }
        public bool PaymentConfirmed { get; set; }
        public DateTime EnrolledDate { get; set; }
        public DateTime LastUpdate { get; set; }
        /// <summary>
        /// Minutos que el estudiante compra
        /// </summary>
        public int TimePurchased { get; set; }

        public virtual CourseSchedule CourseSchedule { get; set; }
        public virtual Account Student { get; set; }
        public virtual ICollection<CourseReview> CourseReview { get; set; }
        public virtual ICollection<CourseStudentFriend> CourseStudentFriend { get; set; }
        public virtual ICollection<InvoiceDetail> InvoiceDetail { get; set; }
    }
}