// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ESA.Core.Entities
{
    public partial class InvoiceDetail
    {
        public InvoiceDetail()
        {
            SaleTax = new HashSet<SaleTax>();
        }

        public int Id { get; set; }
        public int InvoiceId { get; set; }
        public int CourseStudentId { get; set; }
        public decimal UnitPrice { get; set; }
        public int Quantity { get; set; }
        public decimal NetAmount { get; set; }
        public bool Taxed { get; set; }
        public DateTime LastUpdate { get; set; }

        public virtual CourseStudent CourseStudent { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual ICollection<SaleTax> SaleTax { get; set; }
    }
}