// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ESA.Core
{
    public partial class InvoiceConfig
    {
        public InvoiceConfig()
        {
            Invoice = new HashSet<Invoice>();
        }

        public int Id { get; set; }
        public string Rtn { get; set; }
        public string Cai { get; set; }
        public string DeclarationNumber { get; set; }
        public string BusinessName { get; set; }
        public int LocationId { get; set; }
        public string PhoneNumber { get; set; }
        public string PhoneMobile { get; set; }
        public string EmailAddress { get; set; }
        public string ProfessionName { get; set; }
        public int AmountRequested { get; set; }
        public int AmountGranted { get; set; }
        public DateOnly ReceptionDate { get; set; }
        public DateOnly IssueDeadline { get; set; }
        public string StartRange { get; set; }
        public string EndRange { get; set; }
        public string CastRange { get; set; }
        public int Invoices { get; set; }
        public DateOnly CurrentDate { get; set; }
        public bool IsActive { get; set; }
        public DateTime LastUpdate { get; set; }

        public virtual Location Location { get; set; }
        public virtual ICollection<Invoice> Invoice { get; set; }
    }
}