// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ESA.Core
{
    public partial class Location
    {
        public Location()
        {
            InvoiceConfig = new HashSet<InvoiceConfig>();
        }

        public int Id { get; set; }
        public string CountryCode { get; set; }
        public string ProvinceName { get; set; }
        public string DistrictName { get; set; }
        public string Neighborhood { get; set; }
        public string Street { get; set; }
        public string AddressReference { get; set; }
        public bool IsActive { get; set; }
        public DateTime LasUpdate { get; set; }

        public virtual ICollection<InvoiceConfig> InvoiceConfig { get; set; }
    }
}