// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ESA.Core
{
    public partial class Refund
    {
        public int Id { get; set; }
        public int PaymentId { get; set; }
        public short RefundStatusId { get; set; }
        public string Reason { get; set; }
        public string Comment { get; set; }
        public decimal Percent { get; set; }
        public decimal? PercentReturned { get; set; }
        public int CreatedBy { get; set; }
        public DateTime LastUpdate { get; set; }

        public virtual Account CreatedByNavigation { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual RefundStatus RefundStatus { get; set; }
    }
}