// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ESA.Core.Entities
{
    public partial class SaleTax
    {
        public int Id { get; set; }
        public int InvoiceDetailId { get; set; }
        public short TaxId { get; set; }
        public decimal TaxPercent { get; set; }
        public decimal TaxAmount { get; set; }
        public DateTime LastUpdate { get; set; }

        public virtual InvoiceDetail InvoiceDetail { get; set; }
        public virtual Tax Tax { get; set; }
    }
}