// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ESA.Core
{
    public partial class StudentPacks
    {
        public int Id { get; set; }
        public int IdPack { get; set; }
        public int IdAccount { get; set; }
        public int LeftMinutes { get; set; }
        public bool IsActive { get; set; }
        public DateOnly UpdatedAt { get; set; }

        public virtual Account IdAccountNavigation { get; set; }
        public virtual LessonsPack IdPackNavigation { get; set; }
    }
}