// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ESA.Core
{
    public partial class Tax
    {
        public Tax()
        {
            SaleTax = new HashSet<SaleTax>();
        }

        public short Id { get; set; }
        public string Name { get; set; }
        public decimal Percent { get; set; }
        public bool IsActive { get; set; }
        public DateTime LastUpdate { get; set; }

        public virtual ICollection<SaleTax> SaleTax { get; set; }
    }
}